#!/usr/bin/env python
#
'''
## License
# https://www.dexterindustries.com
#
# Copyright (c) 2020 Dexter Industries
# Released under the MIT license (http://choosealicense.com/licenses/mit/).
# For more information see https://github.com/DexterInd/DI_Sensors/blob/master/LICENSE.md
'''

'''
THIS IS A COPY OF THE FILE FOUND IN RASPBIAN FOR ROBOTS
DO NOT EDIT THIS FILE
IF CHANGES ARE NEEDED EDIT THE ONE IN RfR THEN PULL IT HERE
-Nicole
'''
import setuptools
setuptools.setup(
	name="Dexter_AutoDetection_and_I2C_Mutex",
	version = "1.3.2",
	description="Dexter Industries Robot Autodetection and I2C Mutex Security",
	author="Dexter Industries",
	url="http://www.dexterindustries.com/GoPiGo/",
	py_modules=['auto_detect_robot', 'auto_detect_rpi', 'I2C_mutex', 'di_i2c', 'di_mutex'],
	install_requires=['smbus-cffi', 'pyserial', 'python-periphery', 'wiringpi'],
)
