/oak:
  ros__parameters:
    camera:
      i_enable_imu: true
      i_enable_ir: false
      i_nn_type: spatial
      i_pipeline_type: RGBD
      cam_pos_x: 0.08
      cam_pos_z: 0.162
      use_rviz: false
    nn:
      i_nn_config_path: depthai_ros_driver/mobilenet
    rgb:
      i_low_bandwidth: true
    left:
      i_low_bandwidth: true
    right:
      i_low_bandwidth: true
    stereo:
      i_low_bandwidth: true
