/oakd:
  ros__parameters:
    camera:
      i_enable_imu: yes
      i_enable_ir: false
      i_nn_type: mobilenet
      i_pipeline_type: RGB
      i_usb_speed: SUPER_PLUS
      cam_pos_x: 0.08
      cam_pos_z: 0.162
      use_rviz: false
    nn:
       i_nn_config_path: depthai_ros_driver/mobilenet
    rgb:
      i_board_socket_id: 0
      i_fps: 10.0
      i_height: 800
      i_interleaved: false
      i_max_q_size: 10
      i_preview_size: 250
      i_enable_preview: false
      i_low_bandwidth: true
      i_keep_preview_aspect_ratio: true
      i_publish_topic: true
      # i_resolution: '1080'
      i_resolution: '800P'
      i_width: 1280
    use_sim_time: false
