name: CI

on: push

jobs:
  build:
    name: apriltag_msgs
    runs-on: ubuntu-latest

    container:
      image: ubuntu:22.04

    steps:
    - uses: actions/checkout@v3

    - uses: ros-tooling/setup-ros@v0.4

    - uses: ros-tooling/action-ros-ci@v0.2
      with:
        package-name: apriltag_msgs
        target-ros2-distro: humble
